# melpazoid <https://github.com/riscy/melpazoid> build checks.

name: melpazoid
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install emacs && emacs --version
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          RECIPE: (gptel-fn-complete :fetcher github :repo "mwolson/gptel-fn-complete")
          EXIST_OK: true
        run: echo $GITHUB_REF && make -C ~/melpazoid
